security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        jwt_user_provider:
            id: App\Base\Security\JwtUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^(?!/login)
            stateless: true
            simple_preauth:
                authenticator: App\Base\Security\JwtUserAuthenticator
            provider: jwt_user_provider

    access_decision_manager:
        strategy: unanimous

    access_control:
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
